INSERT INTO currency (code, name, symbol)
VALUES ('USD', 'United States Dollar', '$'),
       ('EUR', 'Euro', '€'),
       ('JPY', 'Japanese Yen', '¥'),
       ('GBP', 'British Pound Sterling', '£'),
       ('AUD', 'Australian Dollar', 'A$'),
       ('CAD', 'Canadian Dollar', 'C$'),
       ('CHF', 'Swiss Franc', 'CHF'),
       ('CNY', 'Chinese Yuan', '¥'),
       ('HKD', 'Hong Kong Dollar', 'HK$'),
       ('NZD', 'New Zealand Dollar', 'NZ$'),
       ('SEK', 'Swedish Krona', 'kr'),
       ('KRW', 'South Korean Won', '₩'),
       ('SGD', 'Singapore Dollar', 'S$'),
       ('NOK', 'Norwegian Krone', 'kr'),
       ('MXN', 'Mexican Peso', '$'),
       ('INR', 'Indian Rupee', '₹'),
       ('RUB', 'Russian Ruble', '₽'),
       ('ZAR', 'South African Rand', 'R'),
       ('TRY', 'Turkish Lira', '₺'),
       ('BRL', 'Brazilian Real', 'R$');
