on: [push]

permissions:
  contents: write
  pull-requests: write


jobs:
  hello_world_job:
    runs-on: macos-latest
    name: A job to say hello
    steps:
      - id: foo
        uses: aemresafak/threepio-action@v1
        with:
          vertex-ai-service-account-key-base64: ${{ secrets.VERTEX_AI_SERVICE_ACCOUNT_KEY_BASE64 }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "[Bot] Update localization files from commit ${{ steps.commit-info.outputs.sha_short }}"
          title: "[Bot] Localization Update (${{ steps.commit-info.outputs.sha_short }})"
          body: |
            🤖 **This PR was automatically created by the threepio-runner workflow.**
  
            Localization files have been updated from commit ${{ steps.commit-info.outputs.sha_short }}.
  
            Original commit message: "${{ steps.commit-info.outputs.commit_message }}"
          branch: localization-${{ steps.commit-info.outputs.sha_short }}
          base: main
          labels: automated-pr, bot
