name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - run: touch hello.txt
  second-job:
    runs-on: ubuntu-latest
    needs: my-job
    steps:
      - run: ls
    
