name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - run: touch hello.txt
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - run: pwd
      - run: ls

    
