name: Localize Application Content

on:
  push:
    branches:
      - main

permissions: 
  contents: write
  pull-requests: write

jobs:
  localize:
    runs-on: macos-latest
    steps:
      - name: Run Locawise Localization
        uses: aemresafak/locawise-action@v1
        with:
          source-lang-code: 'en'
          file-name-pattern: 'messages_{language}.properties'
          target-lang-codes: 'es,fr,de,it,tr,ja' # Comma-separated
          localization-root-path: 'src/main/resources/i18n'
          context: |
            You work for ShopSphere, a global e-commerce platform. Your task is to localize the application content for various international markets.
            ShopSphere is a comprehensive online marketplace that connects buyers and sellers from around the world. It offers a wide variety of products, including electronics, fashion, home goods, books, and more. The platform aims to provide a seamless and secure shopping experience, with features like personalized recommendations, easy checkout, multiple payment options, and reliable shipping.
          glossary: |
            customer: An individual or entity that browses, purchases, or considers purchasing products on the ShopSphere platform.
            seller: An individual, business, or brand that lists and sells products through the ShopSphere marketplace.
            product: Any item, good, or service offered for sale on ShopSphere.
            SKU: "Stock Keeping Unit. A unique alphanumeric code assigned to each distinct product for inventory tracking."
          vertex-ai-service-account-key-base64: ${{ secrets.VERTEX_AI_SERVICE_ACCOUNT_KEY_BASE64 }}

      - name: Get commit info
        id: commit-info
        run: |
          SHA_SHORT=$(git rev-parse --short HEAD)
          echo "sha_short=$SHA_SHORT" >> $GITHUB_OUTPUT
          COMMIT_MSG=$(git log -1 --pretty=%s | tr -d '\n')
          echo "commit_message=$COMMIT_MSG" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "[Bot] Update localization files from commit ${{ steps.commit-info.outputs.sha_short }}"
          title: "[Bot] Localization Update (${{ steps.commit-info.outputs.sha_short }})"
          body: |
            🤖 This PR was automatically created by the locawise workflow.
            Localization files have been updated from commit ${{ steps.commit-info.outputs.sha_short }}.
            Original commit message: "${{ steps.commit-info.outputs.commit_message }}"
          branch: localization-${{ steps.commit-info.outputs.sha_short }}
          base: main # Or your default branch
          labels: automated-pr, bot


