name: threepio-runner
run-name: threepio is being run! Localization is coming.
on:
  push:
    branches:
      - main

jobs:
  set-up-threepio:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          repository: aemresafak/threepio
          path: threepio
          token: ${{ secrets.ACCESS_TOKEN }}  # Personal access token with repo scope

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry --directory=threepio install

      - name: Get commit info
        id: commit-info
        run: |
          SHA_SHORT=$(git rev-parse --short HEAD)
          echo "sha_short=$SHA_SHORT" >> $GITHUB_OUTPUT
          # Sanitize commit message for GITHUB_OUTPUT by replacing newlines
          COMMIT_MSG=$(git log -1 --pretty=%s | tr -d '\n')
          echo "commit_message=$COMMIT_MSG" >> $GITHUB_OUTPUT

      - name: Run threepio
        run: poetry --directory=threepio run python src/threepio/main.py ../i18n.yaml

      - name: Check for changes
        id: check-changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "changes_detected=false" >> $GITHUB_OUTPUT
            echo "No changes detected in localization files. Skipping PR creation."
          fi

      - name: Clean up threepio
        run: rm -rf threepio

      - name: Create Pull Request
        if: steps.check-changes.outputs.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: "[Bot] Update localization files from commit ${{ steps.commit-info.outputs.sha_short }}"
          title: "[Bot] Localization Update (${{ steps.commit-info.outputs.sha_short }})"
          body: |
            🤖 **This PR was automatically created by the threepio-runner workflow.**
            
            Localization files have been updated from commit ${{ steps.commit-info.outputs.sha_short }}.
            
            Original commit message: "${{ steps.commit-info.outputs.commit_message }}"
          branch: localization-${{ steps.commit-info.outputs.sha_short }}
          base: main
          labels: automated-pr, bot