name: threepio-runner
run-name: threepio is being run! Localization is coming.
on:
  push:
    branches:
      - main

jobs:
  set-up-threepio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          repository: aemresafak/threepio
          path: threepio
          token: ${{ secrets.ACCESS_TOKEN }}  # Personal access token with repo scope

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.2
          virtualenvs-create: true
          virtualenvs-in-project: true

      - run: pwd
      
      - name: Install dependencies
        run: poetry --directory=threepio install
      
      - name: Run threepio
        run: poetry --directory=threepio run python src/threepio/main.py i18n.yaml


